# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AgentCli < Formula
  desc "A powerful Go framework for building production-ready AI agents"
  homepage "https://github.com/Ingenimax/agent-sdk-go"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Ingenimax/agent-sdk-go/releases/download/v0.1.0/agent-sdk-go_Darwin_x86_64.tar.gz"
      sha256 "e29f45a2c033a4ab1ddbcde3685987ee5604988bbb393b91d044ba97667e719f"

      def install
        bin.install "agent-cli"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Ingenimax/agent-sdk-go/releases/download/v0.1.0/agent-sdk-go_Darwin_arm64.tar.gz"
      sha256 "d2c661dd716047781e4a0ba6e06a3831e0459cdfb5bf10ebe19a542d9d8b2baa"

      def install
        bin.install "agent-cli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Ingenimax/agent-sdk-go/releases/download/v0.1.0/agent-sdk-go_Linux_x86_64.tar.gz"
      sha256 "20d815731fb507aaf3d3d2d18109bd57b5d6632a3d494d5c553ba5c749f988f5"
      def install
        bin.install "agent-cli"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Ingenimax/agent-sdk-go/releases/download/v0.1.0/agent-sdk-go_Linux_arm64.tar.gz"
      sha256 "0f288c38aa20fd175c63ac403bae29f3f0621a80af8fbe9fd6aff3dd41ca5593"
      def install
        bin.install "agent-cli"
      end
    end
  end

  test do
    system "#{bin}/agent-cli --version"
  end
end
